"""empty message

Revision ID: f8fa40b4e69c
Revises: 
Create Date: 2024-12-11 02:30:03.028660

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f8fa40b4e69c"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "heroes",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("tg_username", sa.String(), nullable=False),
        sa.Column("gift_to_id", sa.Integer(), nullable=True),
        sa.Column("hero_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["gift_to_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["hero_id"],
            ["heroes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tg_username"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users")
    op.drop_table("heroes")
    # ### end Alembic commands ###
